site_name: pytest-trust-random
docs_dir: docs

nav:
  - Introduction: index.md
  - usage.md
  - reference.md

theme: material

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
